theme: jekyll-theme-minimal

title: AfterFacts
description: Para que no nos olvidemos de las predicciones
site_url: https://blog.pabloreyes.es
baseurl: /afterfacts.github.io
google_analytics: 'UA-3511101-1'

author:
  name: 'Pablo Reyes'
  email: 'info@pabloreyes.es'
  github_username:  pabloreyes
  linkedin_username:  pabloreyesalmagro

# Build settings
destination: _site
permalink: /:title/
markdown: kramdown

kramdown:
  # use Github Flavored Markdown
  input: GFM

plugins: ['jekyll-target-blank']
